# Site Settings
title: TechWisdomByAjinkya | Just a tech blog!
email: ajinkyabapat12@gmail.com
description: What is an ocean but a multitude of drops.
baseurl: "/techwisdombyajinkya" # the subpath of your site, e.g. /blog
url: "http://iamajinkya.me" # the base hostname & protocol for your site
google_analytics: "UA-109858103-1"

# User Settings
username: TechWisdom
username1: Ajinkya
user_description: A DevOps Guy.
disqus_username: 'https-ajinkyabapat-github-io'

# Social Media
# Remove the item if you don't need it
github_username: AjinkyaBapat
facebook_username: iamajinkyabapat
twitter_username: ajinkyab12
instagram_username: ajinkyab12
linkedin_username: ajinkyabapat
medium_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: iamajinkya.me
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
